# Generated by Django 5.2.14 on 2026-05-25 21:09

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name or company name', max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, help_text="Client's age (must be 18 or older)", null=True, validators=[django.core.validators.MinValueValidator(18, message='Client must be at least 18 years old'), django.core.validators.MaxValueValidator(120, message='Invalid age')])),
                ('phone', models.CharField(help_text='Enter phone number with country code', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format (e.g., +1234567890)', regex='^\\+?1?\\d{9,15}$')])),
                ('city', models.CharField(help_text='City of residence/office', max_length=50)),
                ('address', models.TextField(help_text='Full street address')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(help_text="Employee's age (18-65)", validators=[django.core.validators.MinValueValidator(18, message='Employee must be at least 18 years old'), django.core.validators.MaxValueValidator(65, message='Employee must be under 65 years old')])),
                ('photo', models.ImageField(blank=True, help_text='Employee photo (optional)', null=True, upload_to='employees/')),
                ('phone', models.CharField(help_text='Enter phone number with country code', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('position', models.CharField(help_text='e.g., Manager, Sales Representative, Production Worker', max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a furniture design(e.g. Loft, Vanguard)', max_length=30, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='design_name_case_insensitive_unique', violation_error_message='Design already exists (case insensitive match)')],
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_production', models.BooleanField(default=False, verbose_name='In production')),
                ('product_code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Product Code')),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.design')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order_date', models.DateField(auto_now_add=True, help_text='Date when order was placed')),
                ('delivery_date', models.DateField(blank=True, help_text='Expected delivery date', null=True, verbose_name='Delivery Date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.client')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.furniture')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a furniture type(e.g. Kitchen, Office, Cabinet etc.)', max_length=30, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='type_name_case_insensitive_unique', violation_error_message='Type already exists (case insensitive match)')],
            },
        ),
        migrations.AddField(
            model_name='furniture',
            name='type',
            field=models.ManyToManyField(help_text='Choose a type for this furniture', to='main.type'),
        ),
    ]
