# Generated by Django 5.2.14 on 2026-05-25 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Full name or company name', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(help_text='Enter Belarusian phone number (e.g., +375291234567)', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Belarusian phone number (e.g., +375291234567)', regex='^(\\+375)(29|33|44|25)\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(help_text='Enter Belarusian phone number (e.g., +375291234567)', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Belarusian phone number (e.g., +375291234567)', regex='^(\\+375)(29|33|44|25)\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Expected delivery date', null=True),
        ),
    ]
