# Generated by Django 5.2.14 on 2026-05-26 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_client_name_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(help_text='Enter phone number (e.g., +375 (29) 123-45-67)', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +375 (29) 123-45-67)', regex='^\\+375 \\(29\\) \\d{3}-\\d{2}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(help_text='Enter phone number (e.g., +375 (29) 123-45-67)', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +375 (29) 123-45-67)', regex='^\\+375 \\(29\\) \\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
