# Generated by Django 5.2.14 on 2026-05-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_client_phone_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['company_name']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='Default', help_text='Full company name', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='responsible_person',
            field=models.CharField(blank=True, default='', help_text='Full name of the responsible contact person', max_length=100, verbose_name='Responsible Person'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(help_text='e.g., Manager, Sales Representatуive, Production Worker', max_length=100),
        ),
    ]
