# Generated by Django 5.2.14 on 2026-05-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_client_options_remove_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('director', 'Director'), ('smm', 'SMM'), ('manager', 'Manager'), ('storekeeper', 'Storekeeper'), ('carpenter', 'Carpenter')], default='manager', help_text="Select employee's position", max_length=20, verbose_name='Position'),
        ),
    ]
