# Generated by Django 5.2.14 on 2026-05-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='News headline', max_length=200)),
                ('short_content', models.CharField(help_text='One sentence summary (max 300 characters)', max_length=300)),
                ('image', models.ImageField(help_text='News image (optional)', upload_to='news_images/')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
