# Generated by Django 5.2.14 on 2026-05-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Enter the term or question', max_length=300)),
                ('answer', models.TextField(help_text='Enter the explanation or answer')),
            ],
            options={
                'ordering': ['question'],
            },
        ),
    ]
