# Generated by Django 5.2.14 on 2026-05-27 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter job position (e.g., Director, SMM, Manager, Storekeeper, Carpenter)', max_length=50, unique=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, help_text='Monthly salary in currency units', max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, help_text="Select employee's position", null=True, on_delete=django.db.models.deletion.PROTECT, to='main.position'),
        ),
    ]
