# Generated by Django 5.2.14 on 2026-05-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_position_alter_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title (e.g., Furniture Designer, Sales Manager)', max_length=200)),
                ('description', models.TextField(help_text='Full job description, requirements, and responsibilities')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Monthly salary in currency units (e.g., 1500.00)', max_digits=10)),
                ('location', models.CharField(default='Minsk, Belarus', help_text='Work location', max_length=100)),
                ('created_date', models.DateField(auto_now_add=True, help_text='Date when vacancy was posted')),
                ('is_active', models.BooleanField(default=True, help_text='Show this vacancy on the website')),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'News'},
        ),
    ]
