# Generated by Django 5.2.14 on 2026-05-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_vacancy_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Promo code (e.g., SUMMER2024, DISCOUNT10)', max_length=50, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, help_text='Discount amount (e.g., 10.00 for 10%)', max_digits=5)),
                ('description', models.CharField(help_text='Brief description of the promo', max_length=200)),
                ('valid_from', models.DateField(help_text='Date when promo code becomes valid')),
                ('valid_to', models.DateField(help_text='Date when promo code expires')),
                ('is_active', models.BooleanField(default=True, help_text='Is this promo code currently active?')),
                ('created_date', models.DateField(auto_now_add=True, help_text='Date when promo was created')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['valid_from', 'code'],
            },
        ),
    ]
