# Generated by Django 5.2.14 on 2026-05-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(help_text='Date when order was placed'),
        ),
    ]
