# Generated by Django 5.2.14 on 2026-05-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_client_timezone_client_timezone_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='timezone_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
