# Generated by Django 5.2.14 on 2026-06-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_order_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Furniture Factory', max_length=100)),
                ('founded_year', models.PositiveIntegerField(default=2010)),
                ('description', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('values', models.JSONField(blank=True, default=list)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('working_hours', models.TextField(blank=True)),
                ('products_info', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
    ]
