# Generated by Django 5.2.14 on 2026-06-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, unique=True, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('added_date', models.DateField(auto_now_add=True, verbose_name='Date added')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display order')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', '-added_date'],
            },
        ),
    ]
