# Generated by Django 5.2.14 on 2026-06-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Term',
        ),
    ]
