# Generated by Django 5.2.14 on 2026-06-06 22:55

import datetime
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_employee_age_employee_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1990, 1, 1), help_text='Date of birth (employee must be at least 18 years old)', validators=[main.models.validate_min_age]),
        ),
    ]
