# Generated by Django 5.2.14 on 2026-09-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo of the furniture', null=True, upload_to='furniture/images/', verbose_name='Image'),
        ),
    ]
