# Generated by Django 5.2.14 on 2026-09-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/certificates/', verbose_name='Certificate image'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificates',
            field=models.TextField(blank=True, help_text='Certificate description'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(blank=True, help_text='Company history by years'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(blank=True, help_text='Legal and bank details'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube embed link'),
        ),
    ]
