# Generated by Django 5.2.14 on 2026-09-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_companyinfo_certificate_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_file',
            field=models.FileField(blank=True, help_text='MP4, WebM или OGG (до 50 МБ)', null=True, upload_to='company/videos/', verbose_name='Video file'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_title',
            field=models.CharField(blank=True, default='Watch Our Video', max_length=200, verbose_name='Video title'),
        ),
    ]
