# Generated by Django 5.2.14 on 2026-09-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_companyinfo_video_url_companyinfo_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='full_content',
            field=models.TextField(blank=True, help_text='Full text of the news article'),
        ),
    ]
