# Generated by Django 5.2.14 on 2026-09-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_news_full_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, help_text='Description of duties and responsibilities'),
        ),
    ]
